import React from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Mail, ShieldAlert, FileText, HelpCircle, MailCheck, ChevronDown } from "lucide-react";
import { Button } from "@/components/ui/button";

interface SheetProps {
  isOpen: boolean;
  onClose: () => void;
}

// 1. ABOUT MEDIBUDGET SHEET
export const AboutSheet: React.FC<SheetProps> = ({ isOpen, onClose }) => {
  return (
    <BaseSheet isOpen={isOpen} onClose={onClose} title="About MediBudget">
      <div className="space-y-4 text-xs leading-relaxed text-muted-foreground p-1">
        <p className="text-foreground font-bold">Your Trusted Healthcare Cost Auditor</p>
        <p>
          MediBudget is an advanced mobile health assistant designed to make medical costs transparent, predictable, and fair for every citizen in India.
        </p>
        <p>
          Whether you are scanning a paper medical bill, analyzing symptoms with our AI assistant, calculating out-of-pocket insurance co-pays, or exploring state-sponsored healthcare schemes, MediBudget puts financial power back in your hands.
        </p>
        <div className="bg-secondary/40 p-3 rounded-2xl space-y-1.5 border border-border/20">
          <p className="font-bold text-foreground text-[10px] uppercase tracking-wider text-teal-400">Core Features Included</p>
          <ul className="list-disc pl-4 space-y-1 text-[11px]">
            <li>Generic Medicine OCR & Alternative Suggestion</li>
            <li>Interactive Regional Procedure Cost Estimator</li>
            <li>Dynamic Health Insurance Co-pay Tracker</li>
            <li>National & State Health Scheme Evaluator</li>
            <li>Offline-ready Cache & Secure local-first audits</li>
          </ul>
        </div>
        <p className="text-[10px] text-center text-muted-foreground/75 font-semibold pt-2">
          MediBudget Mobile &bull; Designed and engineered in India.
        </p>
      </div>
    </BaseSheet>
  );
};

// 2. PRIVACY POLICY SHEET
export const PrivacyPolicySheet: React.FC<SheetProps> = ({ isOpen, onClose }) => {
  return (
    <BaseSheet isOpen={isOpen} onClose={onClose} title="Privacy Policy">
      <div className="space-y-3.5 text-xs leading-relaxed text-muted-foreground p-1">
        <p className="text-foreground font-bold">Privacy First by Design</p>
        <p>
          At MediBudget, we believe that your health history and financial audits are deeply private. That's why our application enforces a strict data minimization protocol.
        </p>
        <div className="space-y-2">
          <p className="font-bold text-foreground text-[11px]">🛡️ 1. Local Sandboxing</p>
          <p>
            Your symptom prediction logs and medicine OCR scanning invoices are cached locally inside secure app storage. We do not store or read your prescription scans on cloud databases.
          </p>
          
          <p className="font-bold text-foreground text-[11px]">🌐 2. Data Transmission</p>
          <p>
            Any diagnostic predictions or cost lookups query optimized APIs through anonymous endpoints. Your personal identify is never tied to cost calculation requests.
          </p>
          
          <p className="font-bold text-foreground text-[11px]">📧 3. Support Inquiries</p>
          <p>
            If you reach out to our team at <a href="mailto:medibudget@gmail.com" className="text-primary font-bold hover:underline">medibudget@gmail.com</a>, your correspondence history is encrypted and only used to answer technical support inquiries.
          </p>
        </div>
      </div>
    </BaseSheet>
  );
};

// 3. TERMS OF SERVICE SHEET
export const TermsOfServiceSheet: React.FC<SheetProps> = ({ isOpen, onClose }) => {
  return (
    <BaseSheet isOpen={isOpen} onClose={onClose} title="Terms of Service">
      <div className="space-y-3.5 text-xs leading-relaxed text-muted-foreground p-1">
        <p className="text-foreground font-bold">Agreement of Fair Use</p>
        <p>
          By creating an account on MediBudget Mobile, you agree to comply with our fair-use standards and guidelines.
        </p>
        <div className="space-y-2">
          <p className="font-bold text-foreground text-[11px]">⚖️ 1. Educational Scope</p>
          <p>
            All costs, scheme checklists, and medicine generic recommendations generated by MediBudget are strictly for reference and educational use. We are not a medical billing service nor an insurance underwriting agency.
          </p>
          
          <p className="font-bold text-foreground text-[11px]">🚫 2. Acceptable Actions</p>
          <p>
            You may not scrape our cost catalogs, reverse-engineer the OCR processing flows, or send automated spam requests to our systems.
          </p>
        </div>
      </div>
    </BaseSheet>
  );
};

// 4. MEDICAL DISCLAIMER SHEET
export const MedicalDisclaimerSheet: React.FC<SheetProps> = ({ isOpen, onClose }) => {
  return (
    <BaseSheet isOpen={isOpen} onClose={onClose} title="Medical Disclaimer">
      <div className="space-y-4 text-xs leading-relaxed text-muted-foreground p-1">
        <div className="p-3.5 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-amber-500 flex gap-3 items-start">
          <ShieldAlert className="h-5 w-5 shrink-0 mt-0.5" />
          <div>
            <p className="font-black text-[11px] uppercase tracking-wider">CRITICAL NOTICE</p>
            <p className="text-[10px] leading-relaxed font-semibold mt-0.5">
              MediBudget is NOT a medical advisory application. Its contents do not substitute professional clinical advice.
            </p>
          </div>
        </div>
        <p className="text-foreground font-bold">1. No Medical Treatment Advice</p>
        <p>
          The symptom checker and AI consultation guides are diagnostic aggregators designed to suggest potential categories for standard cost estimation ONLY. They do not constitute actual treatment prescriptions or professional medical diagnosis.
        </p>
        <p className="text-foreground font-bold">2. Always Consult a Practitioner</p>
        <p>
          If you are experiencing severe symptoms, chest pain, or need urgent clinical help, immediately visit the nearest emergency medical facility or consult a certified licensed physician.
        </p>
      </div>
    </BaseSheet>
  );
};

// 5. FAQ SHEET (With premium expandable accordions!)
export const FAQSheet: React.FC<SheetProps> = () => {
  const [activeIndex, setActiveIndex] = React.useState<number | null>(null);

  const faqs = [
    {
      q: "What is MediBudget and is it free?",
      a: "MediBudget is a completely free consumer cost-auditing tool. Our mission is to eliminate surprise bills by giving users transparency over Indian healthcare charges, procedures, and alternatives."
    },
    {
      q: "How accurate are regional procedure costs?",
      a: "Procedure costs are compiled using historical treatment rates, adjusted in real time based on your selected City Tier (Tiers 1/2/3) and hospital setup (Private/Corporate/Govt) to offer a reliable, real-world baseline."
    },
    {
      q: "How does the generic medicine alternative scanner work?",
      a: "By uploading a clear image of your prescription or medicine box, our OCR engine extracts active salt formulas and searches our database to suggest equivalent generic medicines at a fraction of the cost."
    },
    {
      q: "Does the app support offline mode?",
      a: "Yes! If you check a region's procedure cost or search for generic medicines once, the metrics are cached locally. You can access essential calculator utilities and offline indexes even when traveling without signal."
    }
  ];

  return (
    <div className="space-y-2 max-w-full">
      {faqs.map((faq, idx) => {
        const isOpen = activeIndex === idx;
        return (
          <div key={idx} className="rounded-xl border border-border/40 bg-card/60 overflow-hidden transition-all duration-300">
            <button
              onClick={() => setActiveIndex(isOpen ? null : idx)}
              className="w-full flex justify-between items-center p-3 text-xs font-bold text-foreground text-left active:bg-secondary/40 transition-colors"
            >
              <span>{faq.q}</span>
              <ChevronDown className={`h-4 w-4 text-muted-foreground shrink-0 transition-transform duration-300 ${isOpen ? "rotate-180 text-primary" : ""}`} />
            </button>
            <AnimatePresence initial={false}>
              {isOpen && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: "auto", opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  transition={{ duration: 0.25 }}
                >
                  <div className="px-3 pb-3.5 pt-0.5 text-[11px] text-muted-foreground leading-relaxed border-t border-border/20">
                    {faq.a}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        );
      })}
    </div>
  );
};

// 6. CONTACT US SHEET
export const ContactUsSheet: React.FC<SheetProps> = ({ isOpen, onClose }) => {
  const [submitted, setSubmitted] = React.useState(false);
  const [message, setMessage] = React.useState("");

  const handleFeedback = (e: React.FormEvent) => {
    e.preventDefault();
    if (!message.trim()) return;
    setSubmitted(true);
    setTimeout(() => {
      setMessage("");
      setSubmitted(false);
      onClose();
    }, 1800);
  };

  return (
    <BaseSheet isOpen={isOpen} onClose={onClose} title="Contact Support">
      {submitted ? (
        <motion.div
          initial={{ scale: 0.95, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          className="py-8 flex flex-col items-center justify-center text-center space-y-3"
        >
          <div className="h-12 w-12 rounded-full bg-emerald-500/10 flex items-center justify-center text-emerald-500">
            <MailCheck className="h-6 w-6" />
          </div>
          <div>
            <p className="font-bold text-foreground text-sm">Message Sent!</p>
            <p className="text-[10px] text-muted-foreground mt-1">Our support team will respond to your registered email shortly.</p>
          </div>
        </motion.div>
      ) : (
        <form onSubmit={handleFeedback} className="space-y-4 p-1">
          <div className="space-y-1">
            <p className="text-xs font-bold text-foreground">Technical Support & General Inquiries</p>
            <p className="text-[10px] text-muted-foreground leading-relaxed">
              Have questions, found a billing mismatch, or need technical assistance? Email us directly or drop a quick feedback note below.
            </p>
          </div>

          <a
            href="mailto:medibudget@gmail.com"
            className="flex items-center gap-3 p-3 rounded-2xl bg-secondary/30 border border-border/20 text-xs text-foreground active-scale hover:bg-secondary/50 transition-colors"
          >
            <div className="h-8 w-8 rounded-xl bg-teal-500/10 flex items-center justify-center text-teal-400 shrink-0">
              <Mail className="h-4.5 w-4.5" />
            </div>
            <div className="text-left">
              <p className="font-bold">Email Support Directly</p>
              <p className="text-[10px] text-teal-400 font-bold">medibudget@gmail.com</p>
            </div>
          </a>

          <div className="space-y-1.5">
            <label className="text-[9px] font-black text-muted-foreground uppercase tracking-wider px-1">Quick Feedback Note</label>
            <textarea
              required
              rows={3}
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              placeholder="How can we help optimize your MediBudget experience today?"
              className="w-full rounded-xl border border-border/40 bg-card p-3 text-xs text-foreground focus:outline-none focus:border-teal-400 placeholder:text-muted-foreground/60 resize-none"
            />
          </div>

          <Button type="submit" className="w-full h-10 text-xs font-bold">
            Submit Feedback Note
          </Button>
        </form>
      )}
    </BaseSheet>
  );
};

// ==========================================
// BASE SHEET CONTAINER (Premium Translucent Bottom-Slide Sheet Drawer)
// ==========================================
interface BaseSheetProps extends SheetProps {
  title: string;
  children: React.ReactNode;
}

const BaseSheet: React.FC<BaseSheetProps> = ({ isOpen, onClose, title, children }) => {
  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-end justify-center">
          {/* Backdrop Layer with Haze filter */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-[#070e11]/80 backdrop-blur-sm"
          />

          {/* Floating Drawer */}
          <motion.div
            initial={{ y: "100%" }}
            animate={{ y: 0 }}
            exit={{ y: "100%" }}
            transition={{ type: "spring", damping: 25, stiffness: 220 }}
            className="relative w-full max-w-md bg-card border-t border-border/60 rounded-t-3xl shadow-2xl p-5 pb-8 overflow-hidden max-h-[85vh] flex flex-col safe-bottom"
          >
            {/* Native indicator notch */}
            <div className="mx-auto w-10 h-1 bg-muted-foreground/20 rounded-full mb-4" />

            {/* Header */}
            <div className="flex justify-between items-center mb-4 shrink-0">
              <h2 className="text-sm font-black text-foreground">{title}</h2>
              <button
                onClick={onClose}
                className="h-7 w-7 rounded-full bg-secondary/80 flex items-center justify-center text-foreground active-scale"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            {/* Scrollable body content */}
            <div className="flex-1 overflow-y-auto pr-1 scroll-bounce scrollbar-thin">
              {children}
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};
