name: Selenium E2E Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish-reports:
    name: Publish E2E Test Reports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Publish Selenium E2E Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Selenium_E2E_Test_Report
          path: test-reports/Selenium_E2E_300_TestCases_Analysis_Report.xlsx
          
      - name: Publish Detailed Selenium E2E Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Selenium_E2E_Detailed_Test_Report
          path: selenium-tests/Selenium_E2E_Detailed_Test_Report.xlsx
          
      - name: Publish Appium Mobile E2E Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Appium_Mobile_E2E_Test_Report
          path: test-reports/Appium_Mobile_E2E_300_TestCases_Analysis_Report.xlsx
          
      - name: Publish Detailed Appium Mobile E2E Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Appium_Mobile_E2E_Detailed_Test_Report
          path: appium-tests/Appium_Mobile_E2E_Detailed_Test_Report.xlsx
